<?
$this->headScript ()->appendFile ( "/scripts/nicEdit/nicEdit.js" )->appendFile ( "/scripts/nicEdit/load.js" );

$is_page = isset ( $this->page->content );
if ( $is_page ){
	Zend_Registry::set("pipeline", $this -> page -> name);
}
$w = $is_page ? 1000 : 500;
$h = $is_page ? 500 : 251;
?>
<? if ( !$is_page ) : ?>
<img src="/images/sections/production.png" align="right" />
<? endif; ?>
<div id="pipeline-text">
	<textarea name="content" class="admin wysiwyg" id="production-content" style="width: <?=$w?>px; height: <?=$h?>px"><?
	echo $is_page ? $this -> page -> content : $this -> page -> description;
	?></textarea>
</div>
