<p>Компания ALPHA-HYDRO на сегодняшний день является крупным
	производителем и поставщиком гидравлики, давно на рынке, все знаем,
	динамично развиваемся и т.п. … Вы это уже где-то читали, не так ли?…</p>
<p>Уверены, Вы уже знаете про наши услуги и сервис, раз вы зашли на наш
	сайт. А подробнее о них Вы можете прочитать в соответствующих разделах
	нашего сайта. Посему мы просто расскажем немного о себе.</p>
<p>Мы - позитивный коллектив. Мы ценим честность, юмор, доверие,
	пунктуальность. Мы уважаем мнение и точку зрения собеседника. Мы
	презираем вранье, хамство, наглость. Мы любим общаться, советоваться,
	обсуждать вопросы по делу. За консультации денег мы не берем. Мы не
	любим и не общаемся с людьми, которые «любят поговорить не о чем»,
	которые «сжигают» наше время. Мы положительно относимся к критике,
	принимает ее без обид и исправляем свои ошибки. Мы даем другим обратную
	связь с предложением как улучшить.</p>
<p>Ваша техника Вас не слушается? Вы устали от некачественного сервиса,
	текущих цилиндров, дырявых шлангов, непрофессионализма и вранья
	поставщиков? Вам надоело ухаживать за вашей престарелой гидравликой?
	Сдайте ее в дом престарелого металлолома. Мы же дадим вам новую,
	которая будет служить Вам утром, днем, вечером и ночью.</p>
<p>
	Мы ценим Вашу индивидуальность и то, что Вы выбрали нашу компанию.<br />
	Мы готовы взять на себя Ваши заботы по решению производственных задач.<br />
	Экономьте Ваше время и силы.
</p>
<p>
	С уважением,<br /> Коллектив ALPHA-HYDRO
</p>
<div class="gallery-wrap about-page">
	<a data-lightbox="group-box" href="/files/images/about/IMG_5130s.jpg" rel="lightbox"><img src="/files/images/about/thumbs/IMG_5130s_thumb.jpg" alt="" /></a>
	<a data-lightbox="group-box" сlass="group-light" href="/files/images/about/IMG_5140s2.jpg" rel="lightbox"><img src="/files/images/about/thumbs/IMG_5140s2_thumb.jpg" alt="" /></a>
	<a data-lightbox="group-box" сlass="group-light" href="/files/images/about/IMG_5145as.jpg" rel="lightbox"><img src="/files/images/about/thumbs/IMG_5145as_thumb.jpg" alt="" /></a>
	<a data-lightbox="group-box" сlass="group-light" href="/files/images/about/IMG_5164s.jpg" rel="lightbox"><img src="/files/images/about/thumbs/IMG_5164s_thumb.jpg" alt="" /></a>
	<a data-lightbox="group-box" сlass="group-light" href="/files/images/about/IMG_5170s.jpg" rel="lightbox"><img src="/files/images/about/thumbs/IMG_5170s_thumb.jpg" alt="" /></a>
</div>