<div class="for-generating-wrap">
<?	
	foreach($this->categories as $cat) {
		echo $cat['name'].' ('.$cat['id'].')<br/>';
	}	
?>
</div>

	<?
		$page = 3;
		if(isset($_POST['page'])) {
			if(is_numeric($_POST['page'])) {
				$page = $_POST['page'];
			}
		}
	?>

<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.0.min.js"></script>
<script type="text/javascript">
	$(function(){

        var Except = new Array();
        <?php foreach($this->except as $except): ?>
        Except.push(<?php echo $except ?>);
        <?php endforeach; ?>

        var exceptProducts = new Array();
        <?php foreach($this->exceptProducts as $except): ?>
        exceptProducts.push(<?php echo $except ?>);
        <?php endforeach; ?>

        var Categories = new Array();
        <?php foreach ($this->categories as $category) : $category = (object) $category?>
          <? if(isset($this -> parents[$category -> parent_id])): ?>
            Categories.push (new Array("<?=$this -> parents[$category -> parent_id] ?>/<?=$category -> name ?>",<?=$category -> id ?>));
          <? endif; ?>
        <? endforeach; ?>

        function buttonEnable() {
            $("#startButton").prop("disabled", false);
        }
	
        var secondTime = 0;
        var pageFormat = 'A4';
        var print = false;

        function finishBook() {
            $.post("/book/index/finishbook", {
                page : PAGE,
                startPage: <?=$page?>,
                pageFormat: pageFormat,
                print: print
            }, function(result) {
            	console.log(result);
                buttonEnable();
                if(secondTime == 0) {
                    secondTime = 1;
                    PAGE = result.page;
                    $("#startButton").click();
                }else{
                    $("#log").append("Генерация каталога завершена!!!");
                    $('#loading').show().html('<a href="/files/pdf/book'+ result.zip_file +'">Скачать сгенерированный каталог (zip)</a>');
                }
            }, 'json').error(function(post_error) {
                console.log(post_error);
                alert("Error occurred");
                buttonEnable();
                $('#loading').hide();
            });
        }

        function generateCategory(i) {

            if (i > Categories.length - 1) {
                finishBook();
                return;
            }

            $.post("/book/index/bycategory", {
                    id : Categories[i][1],
                    page : PAGE,
                    except: Except,
                    except_products: exceptProducts,
                    second_time : secondTime,
                    pageFormat: pageFormat,
                    print: print
                }, function(result) {
                    console.log(result);
                    PAGE = result.page;
                    if(secondTime == 1) {
                        $("#log").append(Categories[i][0] + " - сгенерировано\n");
                    } else {
                        $("#log").append("Расчет нумерации страниц для категории " + Categories[i][0] + ", id:" + Categories[i][1] + " прошел успешно\n");
                    }
                    generateCategory(i + 1);
                }, 'json')
                .error(function(post_error) {
                    console.log(post_error);
//                    console.log(textStatus);
//                    console.log(error);
                    $("#log").append("ОШИБКА расчета нумерации страниц для категории " + Categories[i][0] + ", id:" + Categories[i][1]+"\n");
                    alert(post_error.responseText);
                    buttonEnable();
                    $('#loading').hide();
                });
        }

        var PAGE = <?=$page?>;
        $("#startButton").click(function(e) {
            $.post("/book/index/newbook",
              {
                pageFormat:pageFormat,
                print: print
              }, function(result) {
                console.log(result);
                $("#startButton").prop("disabled", "disabled");
                $('#loading').show();
                generateCategory(0);

            }, 'json').error(function(error) {
                alert("Error occurred1\n" + error.responseText);
                buttonEnable();
                $('#loading').hide();
            });
        });

        $('input[name="page_format"]').change(function(){
            pageFormat = $(this).val();
        });
        $('input[name="print"]').change(function(){
            if($('input[name="print"]').attr('checked') == 'checked'){
                print = true;
            }else{
                print = false;
            }
        });
        $("#log").text("Categories: " + Categories.length + "\n");
    })
</script>

<div id="loading" style="display: none;">Loading...</div>
<h2>Генерация каталога</h2>
<textarea id="log" rows="20" readonly="readonly" style="width: 100%;"></textarea>
<br/>Формат A5 <input type="radio" name="page_format" value="A5"> Формат A4<input type="radio" name="page_format" checked value="A4"> Для печати <input type="checkbox" name="print">
<button id="startButton">
	Генерировать книгу
</button>