			<div class="block header-sections" id="section">
				<a href='/catalog'> 
					<img src="/images/sections/catalog-small.png" alt="Раздел" />
					<span>Каталог продукции</span>
				</a>
				<a href='/sections/production/'> 
					<img src="/images/sections/production-small.png" alt="Раздел" />
					<span>Наше производство</span>
				</a>	
				<a href='/sections/pipeline/'> 
					<img src="/images/sections/pipeline-small.png" alt="Раздел" />
					<span>Трубопроводная арматура</span>
				</a>													
			</div>	