<?php // $this-> headScript() -> captureStart(); ?>
<script>$(function (){

        // добавление параметра
        $("#addParam").click(function(){
            var i = $("#productparams tr:last").prev().find("input:first").data("index");
            if ( i == undefined ) i = 0;
            else i++;
            
            $('<tr>' +
            '<td><span class="params-name"><input data-index="'+i+'" name="productparams['+i+'][name]" value="" style="width: 90%;"/></span></td>' +
            '<td><span class="params-value"><textarea name="productparams['+i+'][value]" rows="1" style="width: 95%"></textarea></span></td>' +
            '<td><span class="params-order"><input type="number" class="number" value="'+(i+1)+'" name="productparams['+i+'][order]"></span></td>' +
            '<td><a href="javascript:;" class="param_delete">удалить</a></td>' +
            '</tr>').insertBefore( $(this).parent().parent() );
        });

        // удаление строки параметра
        $(".param_delete").live("click", function(){
        	$(this).parent().parent().remove();
        });
        
        $(".new-image").live("change", function(){
        	var e = $(this).parent().clone();
        	$(this).parent().append( "<a href='javascript:;' class='del-image'>удалить</a>" );
     		
        	$(this).parent().parent().append( '<div><input type="file" name="images[]" class="new-image" /></div>' );
        });
        
        $(".del-image").live("click", function(){
        	$(this).parent().remove();
        });

		$("body").append('<div id="bg-grey" style="display: none; position: absolute;top: 0;left: 0;height: 100%;width: 100%;z-index: 1101;background: #222; opacity: 0.6;"></div>');
		$("body").append('<div id="window" class="production-item r big" style="min-height: 300px !important;"><div class="header"><a href="javascript:void(0)" class="close"><span>Закрыть</span></a></div><div class="content"></div></div>');

        // клик по кнопке "+" категории
		$(".open-categories-modal").click(function(){
			$("#window .content").html("<div style='text-align: center; width: 100%'>Загрузка...</div>");
			$("#window").show();
			$("#bg-grey").show();

			$.get($(this).data("href"), {}, function(response){
				$("#window .content").html(response);
			}).error(function(){
				$("#window .content").html("<h2>error occured</h2>");
			});
			
			$('html,body').animate({scrollTop: 0}, 500);
		});

        // клик по категории в выплывающем окне выбора категорий (загрузка следующего уровня)
        $("#window .content .select-list a").live('click', function(){
			var e = $(this);
			$.get($(this).attr("href"), {currentCategory: "<?=  $this->row->id?>"}, function( response ){
				if ( response ){
					$("#window .content").html( response );
				} else {
                    // если достигнут последний уровень, ссылка становится текстом (оригинальное решение :) )
					$(e).parent().html( $(e).text() );
				}
			}).error(function(){
				$("#window .content").html("<h2>error occured</h2>");
			});;
			
			return false;
		});

        // клик по кнопке "ок" или "отмена" в выплывающем окне выбора категорий
		$("#window .content .select-list-buttons a").live("click", function(){
			if ( $(this).hasClass('ok') ){
				var input = $("#window .content input:checked");
				if (input.length > 0){
                    var rel = $('<div class="rel"><input type="hidden" name="categories[]" value="'+input.val()+'" />' +
                    '<span>'+input.parent().next().text()+'</span>' +
                    '<a class="admin delete del-category-rel" href="javascript:;">-</a></div>')

                    $(".p-categories").append(rel);
                }
			}

			$("#window .close").click();
			
			return false;
		});
		
		$("#window .close").click(function() {
			$("#window").hide();
			$("#bg-grey").hide();
		});
		
		$(".del-category-rel").live("click", function(){
			$(this).parent().remove();
		});
		
	});
	</script>
<?php //$this -> headScript() -> captureEnd(); ?>
<!-- @TODO Интегрировать этот блок стилей в основной CSS! -->
<style type="text/css">
    form#product input.wide {width: 600px;}
    form#product input.number {width: 50px;}
    form#product textarea.wide {width: 100%;}
    form#product div.clear {clear: both;}
    form#product label {display: block;}
    form#product div.p-categories {margin: 20px 0;}
    table#productparams tr:hover {background-color: #fbeed5;}
    table#productparams th {background-color: #cacaca;}

</style>
<form id="product" name="product" enctype="multipart/form-data" action="<?=$this->url()?>" method="post">
    <label for="sku">Код товара: </label><input type="text" name="sku" id="sku" value="<?=$this->newproduct->sku->getValue();?>" placeholder="SKU" title="SKU" class="wide"><br/>
    <label for="name">Наименование: </label><input type="text" name="name" id="name" value="<?=$this->newproduct->name->getValue()?>" placeholder="Название" class="wide">
    <div class="clear"></div>
        <p>Основное изображение: </p>
        <img style="max-width: 250px" src="<?=$this->row->image ? '/files/images/product/'.$this->row->image : 'http://fakeimg.pl/124x124/'?>" /><br/>
        <input type="file" name="image" id="image" />
        <div class="clear"></div>
        <p>Дополнительные изображения: </p>

        <?php if ( $this -> row -> a_images ) :
                foreach ( $this -> row -> a_images as $image ) : ?>
                <div>
                    <a href="javascript:;" style="margin-right: 400px; float: right" class="admin delete del-image" title="Удалить изображение">-</a>
                    <img style="max-width: 250px" src="<?='/files/images/product/'.$image?>" /> <br />
                    <input type="hidden" name="images[]" value="<?=$image?>" />
                </div>
                <?php	endforeach;	?>
        <?php endif; ?>
        <div>
            <input type="file" name="images[]" class="new-image" />
        </div>


    <p>Категории <a class="admin new open-categories-modal" href="javascript:;" data-href="/catalog/categories">-</a></p>
    <div class="p-categories" style="font-size: 75%">
        <?php foreach ( $this -> row -> findManyToManyRowset("Model_DbTable_Categories", "Model_DbTable_CategoryXref") as $category ) :	?>
            <div class="rel">
					<input type="hidden" name="categories[]" value="<?=$category->id?>" />
					<span><?=$category->getBcnName()?></span>
					<a class="admin delete del-category-rel" href="javascript:;">-</a>
			</div>
        <?php endforeach;?>
    </div>

    <label for="s_name">Поисковые фразы: </label><input type="text" name="s_name" id="s_name" value="<?=$this->newproduct->s_name->getValue()?>"  placeholder="Имя для поиска" class="wide">
    <label for="note">Примечание: </label><input type="text" name="note" id="note" value="<?=$this->newproduct->note->getValue()?>" class="wide">
    <label for="description">Описание: </label><textarea name="description" id="description" rows="10" class="wide"><?=$this->newproduct->description->getValue()?></textarea>
    <label for="order">Порядок: </label><input type="number" name="order" id="order" value="<?=$this->newproduct->order->getValue()?>" class="number">

				<h3 align="center">Параметры товара</h3>
				<table id="productparams" style="width: 100%" cellpadding="2">
					<tr>
						<th>Название</th>
						<th>Значение</th>
						<th>Порядок</th>
						<th></th>
					</tr>
					<?php foreach ($this->productParams as $i=>$param) :
					?>
					<tr>
						<td><span class="params-name">
							<input data-index="<?=$i?>" name="productparams[<?=$i?>][name]" value="<?=$param -> name ?>" style="width: 90%;"/>
						</span></td>
                        <td><span class="params-value">
							<textarea name="productparams[<?=$i?>][value]" rows="1" style="width: 95%"><?=htmlspecialchars($param -> value) ?></textarea>
						</span></td>
                        <td><span class="params-order">
							<input type="number" class="number" value="<?=$param -> order ?>" name="productparams[<?=$i?>][order]">
						</span></td>
						<td><a href="javascript:;" class="param_delete">удалить</a></td>
					</tr>
					<?php endforeach; ?>
					<tr><td align="center" colspan="4"><a href="javascript:;" id="addParam">Добавить параметр</a></td></tr>
				</table>

<?php if ( count($this->subProducts)>0 ) :
    $subproductParams = $this-> row -> getSubParams();
	$count_prop = count($subproductParams) + 1;
?>
	<table class="sub-products" style="border-spacing: 0">
		<tr>
			<th>Название</th>
			<?php foreach ( $subproductParams as $param ) :	?>
			<th><?=$param -> name ?></th>
			<?php endforeach; ?>
            <th>X</th>
		</tr>
		
		<?php foreach ( $this->subProducts as $sub_product ) :?>
		<tr>
		<td><a href="<?=$this->url(array("controller"=>"products", "action"=>"edit", "parent_id"=>$this-> row ->id, "id"=>NULL, "subid"=>$sub_product->id))?>"><?=$sub_product -> sku ?></a></td>
		<?php foreach($sub_product->getParamsValues() as $param) :?>
		<td><?=$param->value; ?></td>
		<?php endforeach ?>
          <td><a title="Удалить" href="<?=$this->url(array("controller"=>"products", "action"=>"deletesub", "id"=>NULL, "subid"=>$sub_product->id))?>">X</a></td>
		</tr>
		<?php endforeach ?>
	</table>
	<?php
	endif;
?><p align="center"><a href="<?=$this->url(array("id"=>NULL, "parent_id"=>$this->row->id))?>">Добавить товарную модификацию</a></p><br/>

<br/>
    <input type="submit" name="submit" id="submit" value="Сохранить">
    <input type="button" name="back" id="back" value="Отмена" onclick="window.location = '<?=$this->url(array("controller"=>"products", "action"=>"view", "category"=>$this->category,"id"=>$this->row->id))?>';">
</form>
