<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link rel="shortcut icon" href="/favicon.png" />
		<?php
		echo $this->headMeta ();
		
		echo $this->headTitle ( "Альфа-Гидро" );
		echo $this->headScript ()-> prependFile ( "/scripts/jquery-1.8.1.min.js" );
		echo $this->headLink ()->appendStylesheet ( 'http://fonts.googleapis.com/css?family=PT+Sans:400,700&subset=latin,cyrillic' )->appendStylesheet ( '/css/application.css' );
		?>
	</head>

<body>
	<? echo $this->partial("components/adminZone.phtml")?>
	<div id="page">
		<div id="header">
			<? echo $this->partial("components/_header.phtml")?>
		</div>
		<div id="catalog-content">
			<h1 class="section-title"><a href="/catalog/basket" style="color: #3E3D3D; text-decoration: none">Корзина</a></h1>
			<div id="catalog-menu">
				<!--<div id="basket">
					<a href="/catalog/basket"><?=$this->action( "count", "basket", "catalog")?></a>
					<span class="menu"></span>
					<div id="basket-menu">
						<a href="/catalog/basket">Просмотр</a>
						<a href="#">Очистить</a>
					</div>
				</div>
				<? echo $this->partial("components/searchForm.phtml")?>
			-->
			</div>
			<div style="clear: both"></div>
			Система заказа товаров в разработке. Для заказа продукции звоните по телефону + 7 (812) 44-949-44.
			<?php
			//echo $this->layout ()->content;
			?>
			<div style="clear: both"></div>
		</div>
		<div id="pre-footer"></div>
	</div>

	<? echo $this->partial("components/_footer.phtml") ?>
	
	<?php
	echo $this->headScript ()->prependFile ( "/scripts/less-1.3.0.min.js" )->prependFile ( "/scripts/jquery-1.8.1.min.js" )
							 ->appendFile ( "/scripts/mainmenu.js" ) -> appendFile ( "/scripts/basket.js" );
	?>
</body>
</html>