<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link rel="shortcut icon" href="/favicon.png" />
		<?php
		echo $this->headMeta ();
		$title = $this->headTitle ();
		if($title[0] == ''){
			echo $this->headTitle ( "Альфа-Гидро" );
		}else {
			echo $this->headTitle ();
		}
		echo $this->headLink ()->appendStylesheet ( 'http://fonts.googleapis.com/css?family=PT+Sans:400,700&subset=latin,cyrillic' )->appendStylesheet ( '/css/application.css' );
		echo $this->headScript ()-> prependFile ( "/scripts/jquery-1.8.1.min.js" );
		echo $this->headScript ()->prependFile ( "/scripts/less-1.3.0.min.js" )->prependFile ( "/scripts/jquery-1.8.1.min.js" )
							 ->appendFile ( "/scripts/mainmenu.js" ) -> appendFile ( "/scripts/basket.js" );
		?>
	</head>

<body>
	<? echo $this->partial("components/adminZone.phtml")?>
	<div id="page">
		<div id="header">	
			<? echo $this->partial("components/_header.phtml")?>
		</div>
		<div id="catalog-content">
			<h1 class="section-title"><a href="/catalog" style="color: #3E3D3D; text-decoration: none">Каталог продукции</a></h1>
			<div id="catalog-menu">
				<div id="basket">
					<a href="/catalog/basket"><?=$this->action( "count", "basket", "catalog")?></a>
					<span class="menu"></span>
					<div id="basket-menu">
						<a href="/catalog/basket">Просмотр</a>
						<a href="#">Очистить</a>
					</div>
				</div>
				<? //echo $this->partial("components/searchForm.phtml")?>
			</div>
			<div style="clear: both"></div>

			<div id="catalog-sidebar">
			<?php
			echo $this->action ( "sidebar", "sidebar", "catalog", Zend_Controller_Front::getInstance ()->getRequest ()->getParams () );
			?>
			<?php
			echo $this->action ( "index", "measure", "catalog", Zend_Controller_Front::getInstance ()->getRequest ()->getParams () );
			?>
			</div>
			<div id="catalog-items">
			<?
				if($this->action ( "navigation", "sidebar", "catalog", Zend_Controller_Front::getInstance ()->getRequest ()->getParams () )) {
					echo $this->action ( "navigation", "sidebar", "catalog", Zend_Controller_Front::getInstance ()->getRequest ()->getParams () );
				} else {
			?>
				<ul class="navigation">
					<li>
						<a href="/">Главная</a>
					</li>
					<li class="active">
						<a href="/catalog">Каталог продукции</a>
					</li>
				</ul>				
			<?
				}
			?>
			
			<?php
			echo $this->layout ()->content;
			?>
			</div>
			
			<div style="clear: both"></div>
		</div>
		<div id="pre-footer"></div>
	</div>

	<? echo $this->partial("components/_footer.phtml") ?>
	
</body>
</html>