<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="shortcut icon" href="/favicon.png" />
		<?php
		echo $this->headMeta ();
		
		echo $this->headTitle ( "Альфа-Гидро" );
		
		echo $this->headLink ()
			->appendStylesheet ( 'http://fonts.googleapis.com/css?family=PT+Sans:400,700&subset=latin,cyrillic' )
			->appendStylesheet ( '/scripts/fancybox/jquery.fancybox-1.3.4.css' )
			->appendStylesheet ( '/css/application.css' );
		echo $this->headScript ()-> prependFile ( "/scripts/jquery-1.8.1.min.js" );
		?>
	</head>
<body>
	<? echo $this->partial("components/adminZone.phtml")?>
	<div id="page">
		<div id="header">
			<? echo $this->partial("components/_header.phtml") ?>
		</div>
		<div id="content"><?php
				echo $this->layout()->content;
			?><div id="pre-footer"></div></div>
	</div><? 
	echo $this->partial("components/_footer.phtml");
	
	echo $this -> headScript () -> prependFile ( "/scripts/less-1.3.0.min.js" )
								-> prependFile ( "/scripts/jquery-1.8.1.min.js" )
								-> appendFile ( "/scripts/fancybox/jquery.fancybox-1.3.4.pack.js" )
								-> appendFile  ( "/scripts/mainmenu.js" )
								-> appendFile  ( "/scripts/scripts.js");
	?></body>
</html>