<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="shortcut icon" href="/favicon.png" />
		<?php
		echo $this->headMeta ();
		
		echo $this->headTitle ( "Альфа-Гидро" );
		echo $this->headScript ()-> prependFile ( "/scripts/jquery-1.8.1.min.js" );
		echo $this->headLink ()->appendStylesheet ( 'http://fonts.googleapis.com/css?family=PT+Sans:400,700&subset=latin,cyrillic' )->appendStylesheet ( '/css/application.css' );
		?>
	</head>
<body>
	<? echo $this->partial("components/adminZone.phtml")?>
	<div id="page">
		<div id="header">
			<? echo $this->partial("components/_header.phtml") ?>
		</div>
		<div id="content">
			<?php
				echo $this->layout()->content;
			?>
			 <div id="pre-footer"></div> 
		</div>
	</div>
	
	<? echo $this->partial("components/_footer.phtml") ?>
	
	<?php
	echo $this -> headScript () -> prependFile ( "/scripts/less-1.3.0.min.js" )
								-> prependFile ( "/scripts/jquery-1.8.1.min.js" )
								-> appendFile  ( "/scripts/mainmenu.js" )
								-> appendFile  ( "/scripts/scripts.js");
	?>
</body>
</html>